sonar.projectKey=nagaraj0205_EKS-Project1
sonar.organization=nagaraj0205

sonar.sources=src
sonar.tests=src/test
sonar.exclusions=src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
